Repository UBC-MDS/credit_default_prediction, pull requests merged in 2021-12, with the labels that each got.

#37 Add Makefile and edit changes in README
  Makefile
  README.Rmd
  README.md
  doc/credit_default_prediction_report.Rmd
  doc/credit_default_prediction_report.html
  doc/credit_default_prediction_report.md
  environment.yaml
  src/credit_default_eda.ipynb
Labels: documentation, enhancement

#41 Modified usage section of readme for makefile
  README.Rmd
  README.md
Labels: documentation

#42 Changed the report url in readme
  README.Rmd
  README.md
Labels: documentation

#48 Added initially builded Dockerfile
  Dockerfile
Labels: enhancement

#53 Reformat the report
  README.Rmd
  doc/credit_default_prediction_report.Rmd
Labels: documentation

#58 Removed Rmd, updated summary in readme
  README.Rmd
  README.md
Labels: documentation
